services:
  - type: web
    name: poll-project
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: >
      python manage.py migrate &&
      python create_initial_superuser.py --noinput || true &&
      gunicorn pollProject.wsgi:application --chdir pollProject --bind 0.0.0.0:$PORT

