services:
  - type: web
    name: poll-project
    env: python

    buildCommand: >
      pip install -r requirements.txt && 
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      python create_initial_superuser.py
      
    # The startCommand should ONLY run the long-running process (Gunicorn).
    startCommand: gunicorn pollProject.wsgi:application --chdir pollProject --bind 0.0.0.0:$PORT
